name: CI

on: [push]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set the value
        id: step_one
        run: |
          export NEXT_VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')
          echo "action_state=$NEXT_VERSION" >> $GITHUB_ENV
        # export NEXT_VERSION=$(npx -p @semantic-release/exec -p semantic-release semantic-release --dry-run --plugins "@semantic-release/commit-analyzer,@semantic-release/exec" --analyzeCommits @semantic-release/commit-analyzer --verifyRelease @semantic-release/exec --verifyReleaseCmd 'echo ${nextRelease.version}')
        # echo $NEXT_VERSION;

      - name: Use the value
        id: step_two
        run: |
          echo "test 2";
          echo "${{ env.action_state }}" # This will output 'yellow'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
