name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      # https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#existing-version-tags
      # https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md#pre-release-branches
      # https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md

      - name: Set next version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # https://github.com/semantic-release/semantic-release/issues/753
        run: export NEXT_VERSION=$(npx -p @semantic-release/exec -p semantic-release semantic-release --dry-run --plugins "@semantic-release/commit-analyzer,@semantic-release/exec" --analyzeCommits @semantic-release/commit-analyzer --verifyRelease @semantic-release/exec --verifyReleaseCmd 'echo ${nextRelease.version}')

      - name: Print next version
        run: echo $NEXT_VERSION

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

      - name: Deploying to staging
        run: echo "I wish I have a staging environment"

